import type { Metadata } from "next";
import { Outfit,  } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Provider from "@/components/Provider";
import { Analytics } from "@vercel/analytics/next"

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ashutosh Tiwari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", outfit.variable,)}
    >
      <body
        suppressHydrationWarning
        className="min-h-full flex flex-col ">
        <Provider>
          {children}
        </Provider>
        <Analytics />
      </body>
    </html>
  );
}
